### ISSUE TITLE
Docker image needs git

### ISSUE THREAD

**Issue by albinekb** [LinusU/scandium#20]
You can't have git dependencies right now... 😁 

```
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:albinekb/scandium.git /root/.npm/_git-remotes/git-github-com-albinekb-scandium-git-fix-postfix-ab699df6: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:albinekb/scandium.git /root/.npm/_git-remotes/git-github-com-albinekb-scandium-git-fix-postfix-ab699df6: undefined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.9.60-linuxkit-aufs
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/task/npm-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1


    at Promise.all.then.arr (/Users/albinekb/Devel/LS/frontend-admin/node_modules/scandium/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by LinusU** [comment]
Fixed by #22
